version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - cd deploy_test
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
  base-directory: deploy_test