version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - pip install -r requirements.txt
      - zip -r function.zip app.py requirements.txt
artifacts:
  files:
    - function.zip
  name: function
  discard-paths: yes